name: Pull Request Checks 🚀

on:
 pull_request:
    branches: [development, production]

jobs:
 pull-request-control:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code 📦
        uses: actions/checkout@v2

      - name: Setup .NET 🛠️
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Format the code 🎨
        run: dotnet format --verbosity diagnostic --verify-no-changes

      - name: Restore dependencies 📚
        run: dotnet restore --disable-parallel

      - name: Build the solution 🏗️
        run: dotnet build Dojo-BE.sln --no-restore

      - name: Run all tests 🧪
        run: dotnet test --no-build --verbosity normal --no-restore
